---
title: "Portrait biogéographique des oiseaux du monde"
author: "Armelle L. et Marion M."
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Source", href: "https://tice.agrocampus-ouest.fr/course/view.php?id=6726", align: left }
      - { icon: "fa-twitter", href: "https://twitter.com/marie_etienne", align: right }
      - { icon: "fa-linkedin", href: "https://www.linkedin.com/in/marie-etienne-818a7115/", align: right }
params:
  setup_path: ../resources/
---

```{=html}
<style>                     
.navbar {
  background-color:#f5f5f2;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}


</style>
```

```{r setup, include=FALSE}
library(flexdashboard)
library(phytools)
library(readxl)
require(rgdal)
library(rgeos)
library(sf)
library(RColorBrewer)
library(ggplot2)
library(dplyr)
library(ggExtra)
library(grid)
library(gridExtra)
library(tidyverse)
library(extrafont)
library(plotly)
library(ggridges)
library(showtext)
```


```{r read_data, include = FALSE}
# Traits par espèce BirdLife
SPECIES <- read_xlsx("data/AVONET Supplementary dataset 1.xlsx", sheet = 2)
# Grille de Behrman
grid <- rgdal::readOGR("data/spatial/BehrmannMeterGrid_WGS84_land.shp")
# Polygones des pays du monde
countriesGeo <- rgdal::readOGR("data/spatial/all_countries.shp")
# Dictionnaire géographique Birdlife 
```

```{r read_data_7z, include = FALSE}
archive::archive_extract('data/spatial/AllSpeciesBirdLifeMaps2019.7z')
rangeData<-read.csv("AllSpeciesBirdLifeMaps2019.csv")
```


```{r manip_data}
# projection de Behrmann
P4S.Behr <- CRS("+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs")
gridB<-spTransform(grid,P4S.Behr)
countries <- spTransform(countriesGeo,P4S.Behr)
# simplification
countriesS <- gSimplify(countries, tol=10000,topologyPreserve=TRUE)
countriesS2 <- st_as_sf(countriesS)
```

# Cartes

## Column 
<!-- {data-width="650"} -->
## Répartition de la masse corporelle

### Carte

```{r cache=TRUE}
# selection variables et nettoyage
species <- SPECIES %>% select(Species1, Primary.Lifestyle, Trophic.Niche, Mass) %>% 
  na.omit() %>% 
  mutate(Primary.Lifestyle = as.factor(Primary.Lifestyle), Trophic.Niche = as.factor(Trophic.Niche))

# On associe à chaque espèce répertoriée dans le dico géographique sa masse
rangeData <- rangeData %>% select(Species, WorldID) %>% 
  merge(y = species[, c("Species1", "Mass")], by.x = "Species", by.y = "Species1") %>% 
  na.omit()

# On récupère les valeurs médianes de la masse par pays (par ID)
med.C <- rangeData %>% group_by(WorldID) %>% 
  mutate(masse_med = median(Mass)) %>% 
  select(-Mass, -Species) %>% 
  distinct()

# on implémente dans l'objet shapefile 
gridB@data <- gridB@data %>% select(-count, -sum, -mean, -min, -max)
gridB@data <- left_join(gridB@data, med.C)


# On construit un gradient de couleurs
# Pour tenir compte de la densité et non pas de la somme d'individus (les masses allant de 22g à 111kg), on construit des groupes d'intervalles. On construit les 50 quantiles (0%, 2%, 4%, ...) et le groupe 1 correspond au premier quantile (un seul individu), le groupe 2 aux individus qui ne sont pas dans le groupe 1 mais dans le second quantile, le groupe 3 aux individus du troisième quantile mais pas dans le groupe 2, etc...

gridB@data <- gridB@data %>% 
  mutate(col = findInterval(masse_med, quantile(masse_med,probs=seq(0,1,0.02),na.rm=T), all.inside = TRUE)) %>% 
  distinct()

gridB.sf <- st_as_sf(gridB)

# On créé des palettes de couleurs
colors<-c(brewer.pal(9,"PuBu")[-1])
colors<-colorRampPalette(colors)(50)
# Typographie
loadfonts(device = "win")
font_add_google("Montserrat")

# Caption
text = textGrob("Aide à la lecture : les espèces associées au groupe 10 correspond au groupe d'oiseaux dont la masse est supérieure à 18% \ndes individus mais inférieure aux 20% suivants. Le 50ème groupe correspond au dernier pourcentage d'individus ayant la\n plus forte masse.", x = 0.02, y=1, just="left",gp=gpar(fontsize=9))

p <- gridB.sf %>% rename(Masse = col) %>%  
  ggplot() +
  geom_sf(aes(fill = Masse, color = Masse)) +
  scale_colour_gradientn(colours = colors, name = "Groupe associé à la masse",
                         guide=guide_colourbar(title.position = "top", 
                                             direction = "horizontal",
                                             ticks = FALSE)) +
  scale_fill_gradientn(colours = colors) +
  guides(fill = FALSE, scale = "none") +
  theme_void() +
  labs(title = "Répartition géographique de la masse des oiseaux", 
       subtitle = "selon les données de BirdLife")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        legend.position=c(0.18, 0.18), 
        legend.title = element_text(size=8, family="Montserrat", face="bold", vjust = 0.8),
        plot.background = element_rect(fill = "#f5f5f2", color = "#f5f5f2"), 
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.key.height = unit(2.5, "mm")
  )

b <- arrangeGrob(p, text,nrow = 2, heights = unit(c(2, .25),c("null", "null")))
grid.newpage()
grid.draw(b)
```

### Histogramme associé

```{r}
p <- gridB.sf %>% filter(masse_med < 10000) %>% 
  ggplot() +
  aes(x = masse_med,y=..density.., fill=stat(x)) +
  geom_density_ridges_gradient()+
  scale_fill_gradientn(colours = colors[1: round(1/3*length(colors))], name = "",
                       guide=guide_colourbar(title.position = "bottom", 
                                             direction = "horizontal",
                                             ticks = FALSE))+
  theme_ridges() +
  labs(title = "Zoom sur la densité de la masse", subtitle = "pour une masse inférieure à 10kg")+
  theme(plot.title = element_text(hjust = 0.18, vjust=2, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        plot.margin = unit(c(1,0,1,0), "cm"),
        legend.position=c(0.02, -0.2),
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        plot.background = element_rect(fill = "#f5f5f2", color = "#f5f5f2"), 
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.margin = margin(6, 6, 6, 6),
        legend.key.height = unit(5, "mm"), 
        legend.key.width =  unit(3, "cm"),
        axis.text.x = element_blank()
  )+
  ylab("Densité")+
  xlab("")
ggplotly(p)
```

## Répartition de la richesse spécifique

### Carte
```{r}
gridB<-spTransform(grid,P4S.Behr)

# compter le nombre d'espèces par cellule
n_sp <- rangeData %>% 
  select(Species, WorldID) %>% 
  group_by(WorldID) %>%
  mutate(n.sp = n()) %>% 
  select(-Species) 

# associer n_sp à m'objet spatiale
gridB@data <-gridB@data %>% 
  select(-count, -sum, -mean, -min, -max) 
gridB@data <-left_join(gridB@data,n_sp)

gridB@data <- gridB@data %>% 
  mutate(col = findInterval(n.sp, quantile(n.sp,probs=seq(0,1,0.02),na.rm=T), all.inside = TRUE)) %>% 
  distinct()

gridB.sf <- st_as_sf(gridB)

# Typographie
loadfonts(device = "win")
font_add_google("Montserrat")

ggplot(gridB.sf) +
  geom_sf(aes(geometry = geometry, fill = col, color = col)) +
  scale_colour_gradientn(colours = colors, name = "Richesse spécifique") +
  scale_fill_gradientn(colours = colors, name = "Richesse spécifique", 
                       guide=guide_colourbar(title.position = "top", 
                                             direction = "horizontal",
                                             ticks = FALSE)) +
  guides(color = FALSE, scale = "none") +
  theme_void() +
  labs(title = "Distribution de la richesse en espèces d'oiseaux", 
       subtitle = "selon les données de BirdLife")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        legend.position=c(0.18, 0.18), 
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        plot.background = element_rect(fill = "#f5f5f2", color = "#f5f5f2"), 
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA)
  )
```

### Histogramme associé

```{r}
p <- gridB.sf %>% 
  ggplot() +
  aes(x = n.sp,y=..density.., fill=stat(x)) +
  geom_density_ridges_gradient()+
  scale_fill_gradientn(colours = colors, name = "",
                       guide=guide_colourbar(title.position = "bottom", 
                                             direction = "horizontal",
                                             ticks = FALSE))+
  theme_ridges() +
  labs(title = "Densité de la richesse en espèces")+
  theme(plot.title = element_text(hjust = 0.18, vjust=3, size = 15, family="Montserrat", face="bold"),
        plot.margin = unit(c(1,0,1,0), "cm"),
        legend.position=c(0.02, -0.2),
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        plot.background = element_rect(fill = "#f5f5f2", color = "#f5f5f2"), 
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.margin = margin(6, 6, 6, 6),
        legend.key.height = unit(5, "mm"), 
        legend.key.width =  unit(3.1, "cm"),
        axis.text.x = element_blank()
  )+
  ylab("Densité")+
  xlab("")

ggplotly(p)
```

# Distribution

```{r}
species <- SPECIES %>% mutate(Species1 = as.factor(Species1), Family1 = as.factor(Family1), Order1 = as.factor(Order1), Lifestyle = as.factor(Primary.Lifestyle))
```

## Histogramme global
```{r}
p <- species %>% select(Species1, Mass) %>% rename(species = Species1) %>% filter(Mass < 1000) %>% 
  ggplot() +
  aes(x = Mass, y=..density..) +
  geom_histogram(bins = 100, fill ="#664b2c", col ="#999999") + 
  geom_density(alpha=0.5, fill = "#285928", col = "#999999")+
  theme_ridges() +
  labs(title = "Distribution de la masse", 
       subtitle = "pour toute les espèces dont la masse est inférieure à 1kg")+
  xlab("Masse (g)")+
  ylab("Densité")+
  theme(plot.title = element_text(hjust = 0.05, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=0, family="Montserrat"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA)
  )
ggplotly(p)
```

```{r}
mean <- species %>% select(Species1, Mass) %>% rename(species = Species1) %>% filter(Mass < 100) %>% summarise(m=mean(Mass))
mean <- mean$m

p <- species %>% select(Species1, Mass) %>% rename(species = Species1) %>% filter(Mass < 100) %>% 
  ggplot() +
  aes(x = Mass, y=..density..) +
  geom_histogram(bins = 100, fill ="#664b2c", col ="#999999") + 
  geom_density(alpha=0.5, fill = "#285928", col = "#999999")+
  geom_vline(xintercept=mean,linetype="dashed")+
  annotate("text", label = "Moyenne de \nla masse",x=round(mean)+10, y=0.035)+
  scale_x_continuous(breaks =c(10,round(mean),50,75,100))+
  theme_ridges() +
  labs(title = "Distribution de la masse", 
       subtitle = "pour toute les espèces dont la masse est inférieure à 100g")+
  xlab("Masse (g)")+
  ylab("Densité")+
  theme(plot.title = element_text(hjust = 0.05, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=0, family="Montserrat"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA)
  )
ggplotly(p)
```

## Masse ~ Lifestyle

```{r}
#couleurs 
colors<-c("#DCDAEB", "#51abb0", "#95c4aa", "#285928", "#664b2c")

p <- species %>% select(Species1, Mass, Lifestyle) %>% rename(species = Species1) %>% filter(Mass < 500) %>% 
  mutate(Lifestyle = fct_recode(Lifestyle, "Aérien" = "Aerial"),
                      Lifestyle = fct_recode(Lifestyle, "Terrestre" = "Terrestrial"), 
                      Lifestyle = fct_recode(Lifestyle, "Insessoriel" = "Insessorial"),
                      Lifestyle = fct_recode(Lifestyle, "Aquatique" = "Aquatic"),
                      Lifestyle = fct_recode(Lifestyle, "Généraliste" = "Generalist")) %>% 
  ggplot()+
  aes(x = Mass, y = Lifestyle, fill = Lifestyle)+
  geom_density_ridges() +
  scale_x_continuous(breaks =c(25,150,300,500))+
  xlab("Masse")+
  ylab("")+
  theme_ridges() +
  scale_fill_manual(values=colors)+
  labs(title = "Distribution de la masse en fonction du style de vie", 
       subtitle = "pour toute les espèces dont la masse est inférieure à 500g")+
  theme(legend.position = "none",
        plot.title = element_text(hjust = -1, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = -0.35, vjust=0, family="Montserrat"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA))

ggplotly(p)
```


