---
title: "Support"
author: "Marion M. & Armelle L."
date: "2022-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(flexdashboard)
library(phytools)
library(readxl)
require(rgdal)
library(rgeos)
library(sf)
library(RColorBrewer)
library(ggplot2)
library(dplyr)
library(ggExtra)
library(grid)
library(gridExtra)
library(tidyverse)
library(extrafont)
library(plotly)
library(ggridges)
library(showtext)
```


```{r read_data, include = FALSE}
# Traits par espèce BirdLife
SPECIES <- read_xlsx("data/AVONET Supplementary dataset 1.xlsx", sheet = 2)
# Grille de Behrman
grid <- rgdal::readOGR("data/spatial/BehrmannMeterGrid_WGS84_land.shp")
# Polygones des pays du monde
countriesGeo <- rgdal::readOGR("data/spatial/all_countries.shp")
# Dictionnaire géographique Birdlife 
```
```{r read_data_7z, include = FALSE}
archive::archive_extract('data/spatial/AllSpeciesBirdLifeMaps2019.7z')
rangeData<-read.csv("AllSpeciesBirdLifeMaps2019.csv")
```

### Cartes

```{r pre_process, cache=TRUE}
# projection de Behrmann
P4S.Behr <- CRS("+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs")
gridB<-spTransform(grid,P4S.Behr)
countries <- spTransform(countriesGeo,P4S.Behr)
# simplification
countriesS <- gSimplify(countries, tol=10000,topologyPreserve=TRUE)
countriesS2 <- st_as_sf(countriesS)

# selection variables et nettoyage
species <- SPECIES %>% select(Species1, Primary.Lifestyle, Trophic.Niche, Mass) %>% 
  na.omit() %>% 
  mutate(Primary.Lifestyle = as.factor(Primary.Lifestyle), Trophic.Niche = as.factor(Trophic.Niche))


########################
###### CARTE 1 #########
########################

# On associe à chaque espèce répertoriée dans le dico géographique sa masse
rangeData1 <- rangeData %>% select(Species, WorldID) %>% 
  merge(y = species[, c("Species1", "Mass")], by.x = "Species", by.y = "Species1") %>% 
  na.omit()


# On récupère les valeurs médianes de la masse par pays (par ID)
med.C <- rangeData1 %>% group_by(WorldID) %>% 
  mutate(masse_med = median(Mass)) %>% 
  select(-Mass, -Species) %>% 
  distinct()

carte1 <- gridB
# on implémente dans l'objet shapefile 
carte1@data <- carte1@data %>% select(-count, -sum, -mean, -min, -max)
carte1@data <- left_join(carte1@data, med.C)

# On construit un gradient de couleurs
# Pour tenir compte de la densité et non pas de la somme d'individus (les masses allant de 22g à 111kg), on construit des groupes d'intervalles. On construit les 50 quantiles (0%, 2%, 4%, ...) et le groupe 1 correspond au premier quantile (un seul individu), le groupe 2 aux individus qui ne sont pas dans le groupe 1 mais dans le second quantile, le groupe 3 aux individus du troisième quantile mais pas dans le groupe 2, etc...

carte1@data <- carte1@data %>% 
  mutate(col = findInterval(masse_med, quantile(masse_med,probs=seq(0,1,0.02),na.rm=T), all.inside = TRUE)) %>% 
  distinct()

carte1.sf <- st_as_sf(carte1)

########################
###### CARTE 2 #########
########################

carte2 <- gridB

n_sp <- rangeData %>% 
  select(Species, WorldID) %>% 
  group_by(WorldID) %>%
  mutate(n.sp = n()) %>% 
  select(-Species) 

carte2@data <-carte2@data %>% 
  select(-count, -sum, -mean, -min, -max) 
carte2@data <-left_join(carte2@data,n_sp)

carte2@data <- carte2@data %>% 
  mutate(col = findInterval(n.sp, quantile(n.sp,probs=seq(0,1,0.02),na.rm=T), all.inside = TRUE)) %>% 
  distinct()

carte2.sf <- st_as_sf(carte2)

```
```{r colors_typo}
colors<-c(brewer.pal(9,"PuBu")[-1])
colors<-colorRampPalette(colors)(50)
loadfonts(device = "win")
font_add_google("Montserrat")
```
```{r map1_densite1}
p1 <- carte1.sf %>% rename(Masse = col) %>%  
  ggplot() +
  geom_sf(aes(fill = Masse, color = Masse)) +
  scale_colour_gradientn(colours = colors, name = "Groupe associé à la masse",
                         guide=guide_colourbar(title.position = "top", 
                                             direction = "horizontal",
                                             ticks = FALSE)) +
  scale_fill_gradientn(colours = colors) +
  guides(fill = FALSE, scale = "none") +
  theme_void() +
  labs(title = "Répartition géographique de la masse des espèces d'oiseaux", 
       subtitle = "selon les données de BirdLife")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.margin = unit(c(0,0,0,0), "cm"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        legend.position=c(0.18, 0.18), 
        legend.title = element_text(size=8, family="Montserrat", face="bold", vjust = 0.8),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.key.height = unit(2.5, "mm")
  )

p2 <- carte1.sf %>% mutate(grp=as.factor(col)) %>% filter(grp == c("10","20", "30", "40", "43", "45", "47", "50")) %>% ggplot() +
  aes(x = masse_med,y=grp, fill=stat(x)) +
  geom_density_ridges_gradient()+
  scale_fill_gradientn(colours = colors, name = "", 
                       guide=guide_colourbar(title.position = "bottom", 
                                             direction = "horizontal",
                                             ticks = FALSE))+
  theme_ridges() +
  labs(title = "Densité des groupes associés à la masse")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.margin = unit(c(0.5,0,0.5,0), "cm"),
        legend.position=c(0.02, -0.15),
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        panel.background = element_rect(fill = "white",colour = NA),
        plot.background = element_rect(fill = "white",colour = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.margin = margin(6, 6, 6, 6),
        legend.key.height = unit(5, "mm"), 
        legend.key.width =  unit(4.4, "cm"),
        axis.text.x = element_blank()
  )+
  ylab("Groupes")+
  xlab("")
```
```{r map2_densite2}
p3 <- ggplot(carte2.sf) +
  geom_sf(aes(geometry = geometry, fill = col, color = col)) +
  scale_colour_gradientn(colours = colors, name = "Richesse spécifique") +
  scale_fill_gradientn(colours = colors, name = "Richesse spécifique", 
                       guide=guide_colourbar(title.position = "top", 
                                             direction = "horizontal",
                                             ticks = FALSE)) +
  guides(color = FALSE, scale = "none") +
  theme_void() +
  labs(title = "Distribution de la richesse en espèces d'oiseaux", 
       subtitle = "selon les données de BirdLife")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.margin = unit(c(0,0,0,0), "cm"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        legend.position=c(0.18, 0.18), 
        legend.title = element_text(size=8, family="Montserrat", face="bold", vjust = 0.8),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA), 
        legend.key.height = unit(2.5, "mm")
  )

p4 <- carte2.sf %>% 
  ggplot() +
  aes(x = n.sp,y=..density.., fill=stat(x)) +
  geom_density_ridges_gradient(size=1)+
  scale_fill_gradientn(colours = colors, name = "",
                       guide=guide_colourbar(title.position = "bottom", 
                                             direction = "horizontal",
                                             ticks = FALSE))+
  theme_ridges() +
  labs(title = "Densité de la richesse en espèces")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.margin = unit(c(0.5,0,0.5,0), "cm"),
        legend.position=c(0.02, -0.15),
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        plot.background = element_rect(fill = "white", color = "#f5f5f2"), 
        panel.background = element_rect(fill = "white", color = NA),
        legend.background = element_rect(fill = "white", color = NA), 
        legend.margin = margin(6, 6, 6, 6),
        legend.key.height = unit(5, "mm"), 
        legend.key.width =  unit(4.3, "cm"),
        axis.text.x = element_blank()
  )+
  ylab("")+
  xlab("")
```

```{r fig.width=10, fig.height=8}
grid.arrange(p1, p2, heights=c(5,3))
grid.arrange(p3, p4, heights=c(5,3))
```

### Densité
```{r couleurs}
aerien <- "#DCDAEB"
aquatique <- "#51abb0"
generaliste <- "#95c4aa"
insessorial <- "#285928"
terrestre <- "#664b2c"
```
```{r masse_richesse}
colors<-c(aerien, aquatique, generaliste, insessorial, terrestre)

species <- SPECIES %>% mutate(Species1 = as.factor(Species1), 
                              Family1 = as.factor(Family1), 
                              Order1 = as.factor(Order1), 
                              Lifestyle = as.factor(Primary.Lifestyle))

mean <- species %>% select(Species1, Mass) %>% rename(species = Species1) %>% summarise(m=mean(Mass))
mean <- mean$m
g1 <- species %>% select(Species1, Mass) %>% rename(species = Species1) %>% filter(Mass < 500) %>% 
  ggplot() +
  aes(x = Mass, y=..density..) +
  geom_histogram(bins = 100, fill ="#664b2c", col ="#999999") + 
  geom_density(alpha=0.5, fill = "#285928", col = "#999999")+
  theme_ridges() +
  geom_vline(xintercept=mean,linetype="dashed")+
  geom_label(aes(x = round(mean), y = 0.015, 
                 label = paste0("Moyenne de la masse\n de l'échantillon : ", as.character(round(mean))),
                 label.size = 0.5), 
             fill = "#DCDAEB")+
  labs(title = "Distribution de la masse", 
       subtitle = "zoom sur toutes les espèces dont la masse est inférieure à 500g")+
  xlab("Masse (g)")+
  ylab("Densité")+
  theme(plot.title = element_text(hjust = 0.05, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=0, family="Montserrat"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA)
  )

g2 <- species %>% select(Species1, Mass, Lifestyle) %>% rename(species = Species1) %>% 
  mutate(Lifestyle = fct_recode(Lifestyle, "Aérien" = "Aerial"),
                      Lifestyle = fct_recode(Lifestyle, "Terrestre" = "Terrestrial"), 
                      Lifestyle = fct_recode(Lifestyle, "Insessoriel" = "Insessorial"),
                      Lifestyle = fct_recode(Lifestyle, "Aquatique" = "Aquatic"),
                      Lifestyle = fct_recode(Lifestyle, "Généraliste" = "Generalist")) %>% 
  ggplot()+
  aes(x = Mass, y = Lifestyle, fill = Lifestyle)+
  geom_density_ridges() +
  xlab("Masse (g)")+
  ylab("")+
  theme_ridges() +
  scale_fill_manual(values=colors)+
  labs(title = "Distribution de la masse en fonction du style de vie", 
       subtitle = "zoom sur toutes les espèces dont la masse est inférieure à 500g")+
  xlim(0,500)+
  theme(legend.position = "none",
        plot.title = element_text(hjust = -1, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = -0.35, vjust=0, family="Montserrat"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        axis.text.y = element_text(colour = c("black", "red", "black", "black", "black"))
        ) 
```
```{r plot_masse_richesse, fig.height=6}
grid.arrange(g1, g2)
```

### Boxplot

```{r aquatique}
species.traits <- SPECIES %>% select(Species1, Female, Male, Wing.Length, Beak.Length_Culmen,Beak.Width, Beak.Depth, Tarsus.Length, Tail.Length,  Mass, Primary.Lifestyle, Habitat.Density) %>% rename(species = Species1, Lifestyle=Primary.Lifestyle) %>% 
  mutate(class = fct_recode(Lifestyle, 
                            "Non aquatique" = "Aerial",
                            "Non aquatique" = "Generalist",
                            "Non aquatique" = "Terrestrial",
                            "Non aquatique" = "Insessorial",
                            "Aquatique" = "Aquatic"),
         Generalist_specialist = fct_recode(Lifestyle, 
                                            "Généraliste" = "Generalist", 
                                            "Spécialiste" = "Aerial",
                                            "Spécialiste" = "Aquatic", 
                                            "Spécialiste" = "Insessorial",
                                            "Spécialiste" = "Terrestrial"),
         Lifestyle = fct_recode(Lifestyle, 
                                "Terrestre" = "Terrestrial",
                                "Aérien" = "Aerial",
                                "Insessoriel" = "Insessorial",
                                "Aquatique" = "Aquatic",
                                "Généraliste" = "Generalist"),
         Lifestyle = factor(Lifestyle, levels=rev(c("Terrestre","Aérien","Insessoriel", "Généraliste", "Aquatique" )))
         )
colors<-c(aquatique, generaliste, insessorial, aerien, terrestre)
ticksY <-c(-0.50, -0.25, 0.00, 0.25, 0.50)

b1 <- species.traits %>% 
  ggplot(aes(x=Lifestyle,y=lm(log(Wing.Length)~log(Mass))$resid,fill=Lifestyle))+
  geom_boxplot()+
  facet_wrap(~Generalist_specialist, scales = "free_y", ncol=1)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red")+
  coord_flip()+
  theme_ridges() +
  scale_y_continuous(breaks=ticksY, limits=c(-0.50, 0.50),
                     labels=expression(-0.50, -0.25, 'Tendance générale',0.25,0.50)) +
  theme(axis.text.y = element_text(colour = 'black'))+
  scale_fill_manual(values=colors)+
  theme(axis.text.x = element_text(angle= 45,hjust=1, colour = c("black", "black", "red", "black","black")))+
  labs(title = "Taille relative de l'aile",x=NULL, y ="")+
  theme(legend.position='none', 
        plot.margin = unit(c(1,1,1,0), "cm"),
        plot.title = element_text(size = 18, family="Montserrat", face="bold"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        strip.text = element_text(size = 15)
  )

b2 <- species.traits %>% 
  ggplot(aes(x=Lifestyle,y=lm(log(Tarsus.Length)~log(Mass))$resid,fill=Lifestyle))+
  geom_boxplot()+
  facet_wrap(~Generalist_specialist, scales = "free_y", ncol=1)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red")+
  coord_flip()+
  theme_ridges() +
  scale_y_continuous(breaks=ticksY, limits=c(-0.50, 0.50),
                     labels=expression(-0.50, -0.25, 'Tendance générale',0.25,0.50)) +
  scale_fill_manual(values=colors)+
  theme(axis.text.x = element_text(angle= 45,hjust=1, colour = c("black", "black", "red", "black","black")))+
  labs(title = "Taille relative de la tarse",x=NULL, y ="")+
  theme(legend.position='none', 
        axis.text.y = element_blank(),
        plot.margin = unit(c(1,1,1,0), "cm"),
        plot.title = element_text(size = 18, family="Montserrat", face="bold"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        strip.text = element_text(size = 15)
  )

b3 <- species.traits %>% 
  ggplot(aes(x=Lifestyle,y=lm(log(Tail.Length)~log(Mass))$resid,fill=Lifestyle))+
  geom_boxplot()+
  facet_wrap(~Generalist_specialist, scales = "free_y", ncol=1)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red")+
  coord_flip()+
  theme_ridges() +
  scale_y_continuous(breaks=ticksY, limits=c(-0.50, 0.50),
                     labels=expression(-0.50, -0.25, 'Tendance générale',0.25,0.50)) +
  scale_fill_manual(values=colors)+
  theme(axis.text.x = element_text(angle= 45,hjust=1, colour = c("black", "black", "red", "black","black")))+
  labs(title = "Taille relative de la queue",x=NULL, y ="")+
  theme(legend.position='none', 
        axis.text.y = element_blank(),
        plot.margin = unit(c(1,1,1,0), "cm"),
        plot.title = element_text(size = 18, family="Montserrat", face="bold"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        strip.text = element_text(size = 15)
  )

b4 <- species.traits %>% 
  ggplot(aes(x=Lifestyle,y=lm(log(Beak.Length_Culmen)~log(Mass))$resid,fill=Lifestyle))+
  geom_boxplot()+
  facet_wrap(~Generalist_specialist, scales = "free_y", ncol=1)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red")+
  coord_flip()+
  theme_ridges() +
  scale_y_continuous(breaks=ticksY, limits=c(-0.50, 0.50),
                     labels=expression(-0.50, -0.25, 'Tendance générale',0.25,0.50)) +
  scale_fill_manual(values=colors)+
  theme(axis.text.x = element_text(angle= 45,hjust=1, colour = c("black", "black", "red", "black","black")))+
  labs(title = "Taille relative du bec",x=NULL, y ="")+
  theme(legend.position='none', 
        axis.text.y = element_blank(),
        plot.margin = unit(c(1,1,1,0), "cm"),
        plot.title = element_text(size = 18, family="Montserrat", face="bold"),
        plot.background = element_rect(fill = "#f5f5f2", color ="#f5f5f2"),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        strip.text = element_text(size = 15)
  )
```

```{r plot_boxplot, warning=FALSE,fig.width=20, fig.height=6}
grid.arrange(b1,b2, b3, b4, nrow=1)
```
```{r}
save(list = ls(), file = "env.RData") 
```

