---
title: "Visualisation 1"
author: "Marion M. & Armelle L."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Idée : Carte à côté de boxplots avec couleurs correspondantes 

```{r message=FALSE}
packages <- c("ape", "phytools", "readxl", "rgdal", "rgeos", "sf", "RColorBrewer", "viridis", "ggplot2", "gridExtra", "dplyr", "lme4", "cowplot","lmerTest","scales","ggExtra","grid","rptR","MuMIn","nlme", "gridExtra", "tidyverse")
install.packages(setdiff(packages, rownames(installed.packages())))

library(ape)
library(phytools)
library(readxl)
require(rgdal)
library(rgeos)
library(sf)
library(RColorBrewer)
library(viridis)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(lme4)
library(cowplot)
library(lmerTest)
library(scales)
library(ggExtra)
library(grid)
library(rptR)
library(MuMIn)
library(nlme)
library(gridExtra)
library(tidyverse)
library(showtext)
```

## Import et sélection 

```{r message=FALSE, warning=FALSE}
# Traits par espèce BirdLife
species <- read_xlsx("data/AVONET Supplementary dataset 1.xlsx", sheet = 2)
# Grille de Behrman
grid <- rgdal::readOGR("data/spatial/BehrmannMeterGrid_WGS84_land.shp")
# Polygones des pays du monde
countriesGeo <- rgdal::readOGR("data/spatial/all_countries.shp")
# Dictionnaire géographique Birdlife 
rangeData<-read.csv("data/spatial/AllSpeciesBirdLifeMaps2019.csv")
```

## Pre-processing

```{r}
# projection de Behrmann
P4S.Behr <- CRS("+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs")
gridB<-spTransform(grid,P4S.Behr)
countries <- spTransform(countriesGeo,P4S.Behr)
# simplification
countriesS <- gSimplify(countries, tol=10000,topologyPreserve=TRUE)
countriesS2 <- st_as_sf(countriesS)

# selection variables et nettoyage
species <- species %>% select(Species1, Primary.Lifestyle, Trophic.Niche, Mass) %>% 
  na.omit() %>% 
  mutate(Primary.Lifestyle = as.factor(Primary.Lifestyle), Trophic.Niche = as.factor(Trophic.Niche))
```

## Cartes

```{r}
# On associe à chaque espèce répertoriée dans le dico géographique sa masse
rangeData <- rangeData %>% select(Species, WorldID) %>% 
  merge(y = species[, c("Species1", "Mass")], by.x = "Species", by.y = "Species1") %>% 
  na.omit()

# On récupère les valeurs médianes de la masse par pays (par ID)
med.C <- rangeData %>% group_by(WorldID) %>% 
  mutate(masse_med = median(Mass)) %>% 
  select(-Mass, -Species) %>% 
  distinct()

# on implémente dans l'objet shapefile 
gridB@data <- left_join(gridB@data, med.C)
gridB@data <- gridB@data %>% select(-count, -sum, -mean, -min, -max)

# On construit un gradient de couleurs
# Pour tenir compte de la densité et non pas de la somme d'individus (les masses allant de 22g à 111kg), on construit des groupes d'intervalles. On construit les 50 quantiles (0%, 2%, 4%, ...) et le groupe 1 correspond au premier quantile (un seul individu), le groupe 2 aux individus qui ne sont pas dans le groupe 1 mais dans le second quantile, le groupe 3 aux individus du troisième quantiles mais pas dans le groupe 2, etc...
# - 
gridB@data <- gridB@data %>% 
  mutate(col = findInterval(masse_med, quantile(masse_med,probs=seq(0,1,0.02),na.rm=T), all.inside = TRUE)) %>% 
  distinct()

gridB.sf <- st_as_sf(gridB)

# On créé des palettes de couleurs
colors<-c(brewer.pal(9,"PuBuGn")[-c(1:2)])
colors<-colorRampPalette(colors)(50)
```


```{r}
loadfonts(device = "win")
font_add_google("Montserrat")

gridB.sf %>% rename(Masse = col) %>%  
  ggplot() +
  geom_sf(aes(fill = Masse, col = Masse)) +
  scale_colour_gradientn(colours = colors, name = "Masse") +
  scale_fill_gradientn(colours = colors, name = "Masse") +
  labs(title = "Répartition géographique de la masse des oiseaux", 
       subtitle = "selon les données de BirdLife", 
       caption = "Echelle probabiliste")+
  theme(plot.title = element_text(hjust = 0.2, vjust=0, size = 15, family="Montserrat", face="bold"),
        plot.subtitle = element_text(hjust = 0.15, vjust=-0.4, family="Montserrat"),
        plot.caption = element_text(hjust = 0.53, vjust=35, family="Montserrat", face = "italic"),
        legend.position="bottom", 
        legend.title = element_text(size=10, family="Montserrat", face="bold", vjust = 0.8),
        panel.background = element_rect(fill = "white")
        )
```

