name: website
on:
  push:
    branches:
      - master

jobs:   
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/r-dataviz_template:0.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate slides
        run: Rscript -e "rmarkdown::render('flexdashboard.Rmd', output_dir = 'build')"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
